name: GitHub Metrics

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token PAT Anda yang sudah dibuat
          token: ${{ secrets.GH_PAT }}

          # Opsi Umum
          user: AlvindraRamadhan
          config_timezone: Asia/Jakarta
          
          # Opsi Tampilan & Tema
          theme: dracula
          config_animations: yes
          config_colors: "color_main: F8F8F2, color_progress: FF449F, color_title: 7AF5F5, color_icon: 7AF5F5"
          
          # Plugin yang akan ditampilkan (plugin achievements yang eror sudah dihapus)
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history: yes
