# .github/workflows/pacman.yml

name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Langkah 1: Generate file SVG
      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Langkah 2: Pindahkan file yang ada dengan cara yang aman
      - name: Create dist directory and move files safely
        run: |
          mkdir -p dist
          find . -maxdepth 1 -name "pacman-contribution-graph*.svg" -exec mv {} dist/ \;
          
      # Langkah 3: Push isi folder 'dist' ke branch 'output'
      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
