name: WakaTime Stats

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          
          # Flags untuk menampilkan statistik yang Anda inginkan
          SHOW_TITLE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE_PER_REPO: "false"
          SHOW_SHORT_INFO: "false"
          SHOW_LOC_CHART: "false"
